version: '3.9'

services:
  mariadb:
    image: mariadb:11.0
    ports:
      - 33060:3306
    volumes:
      - ./volumes/database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_USER}"
      MARIADB_USER: "${DB_NAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
